In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
B, T, C = 4, 8, 32

x = torch.randn(B, T, C)

In [6]:
head_size = 16

query = nn.Linear(C, head_size)
key = nn.Linear(C, head_size)

In [48]:
k = key(x)
q = query(x)

In [49]:
wei = (q @ k.transpose(-2, -1))

In [50]:
tril = torch.tril(torch.ones(T, T))

In [51]:
wei = wei.masked_fill(tril == 0, float('-inf'))

In [57]:
wei[0]

tensor([[ 0.1252,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.5924, -1.5284,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.5981, -1.4377, -0.3525,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-1.4639, -0.3861,  1.6008,  0.5287,    -inf,    -inf,    -inf,    -inf],
        [ 0.3899,  0.4486, -1.8886, -0.7643,  0.2716,    -inf,    -inf,    -inf],
        [-0.8303, -0.3241,  2.7891,  4.8735, -0.2269,  0.6974,    -inf,    -inf],
        [-1.1036, -1.5494,  0.4757,  3.0534, -0.6115,  2.4923,  0.5016,    -inf],
        [ 2.6905,  2.1906,  1.5348, -1.1701, -1.4183, -1.6357,  1.4875,  0.8925]],
       grad_fn=<SelectBackward0>)

In [66]:
F.softmax(wei, dim=-1)[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.7183, 0.2817, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3690, 0.1593, 0.4717, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0306, 0.0899, 0.6553, 0.2243, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2970, 0.3150, 0.0304, 0.0937, 0.2639, 0.0000, 0.0000, 0.0000],
        [0.0029, 0.0048, 0.1077, 0.8660, 0.0053, 0.0133, 0.0000, 0.0000],
        [0.0088, 0.0056, 0.0428, 0.5632, 0.0144, 0.3213, 0.0439, 0.0000],
        [0.4102, 0.2488, 0.1291, 0.0086, 0.0067, 0.0054, 0.1232, 0.0679]],
       grad_fn=<SelectBackward0>)

In [40]:
wei = F.softmax(wei, dim=2)

In [39]:
wei

tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.7183, 0.2817, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.3690, 0.1593, 0.4717, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0306, 0.0899, 0.6553, 0.2243, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2970, 0.3150, 0.0304, 0.0937, 0.2639, 0.0000, 0.0000, 0.0000],
         [0.0029, 0.0048, 0.1077, 0.8660, 0.0053, 0.0133, 0.0000, 0.0000],
         [0.0088, 0.0056, 0.0428, 0.5632, 0.0144, 0.3213, 0.0439, 0.0000],
         [0.4102, 0.2488, 0.1291, 0.0086, 0.0067, 0.0054, 0.1232, 0.0679]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0945, 0.9055, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.4412, 0.1867, 0.3722, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1104, 0.1788, 0.2113, 0.4995, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2687, 0.2608, 0.2049, 0.2177, 0.0480, 0.0000, 0.0000, 0.0000],
         [0.0395, 0.034